/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-12-25 16:07:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.User.Post;
import java.util.*;
import com.db.DBConnect;
import com.DAO.PostDao;
import com.User.UserDetails;

public final class showNotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/All_Component/allcss.jsp", Long.valueOf(1764747648139L));
    _jspx_dependants.put("/All_Component/footer.jsp", Long.valueOf(1766352206278L));
    _jspx_dependants.put("/All_Component/navbar.jsp", Long.valueOf(1766595821001L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.DAO.PostDao");
    _jspx_imports_classes.add("com.User.UserDetails");
    _jspx_imports_classes.add("com.User.Post");
    _jspx_imports_classes.add("com.db.DBConnect");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

UserDetails user3 = (UserDetails) session.getAttribute("userD");

if (user3 == null) {
	response.sendRedirect("login.jsp");
	session.setAttribute("login-error", "please login...");
}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>show notes page</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-custom navbar-custom\">\r\n");
      out.write("	<a class=\"navbar-brand\" href=\"#\"><i class=\"fa fa-book mr-1\"\r\n");
      out.write("		aria-hidden=\"true\"></i>ENotes</a>\r\n");
      out.write("	<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("		data-target=\"#navbarSupportedContent\"\r\n");
      out.write("		aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("		aria-label=\"Toggle navigation\">\r\n");
      out.write("		<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("	</button>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("		<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.jsp\"><i\r\n");
      out.write("					class=\"fa fa-home mr-1\" aria-hidden=\"true\"></i>Home <span\r\n");
      out.write("					class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"addNotes.jsp\"><i\r\n");
      out.write("					class=\"fa fa-plus-circle mr-1\" aria-hidden=\"true\"></i>Add Notes</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"showNotes.jsp\"><i\r\n");
      out.write("					class=\"fa fa-user-circle-o mr-1\" aria-hidden=\"true\"></i>Show Notes</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("		");

		UserDetails user = (UserDetails) session.getAttribute("userD");
		if (user != null) {
		
      out.write("\r\n");
      out.write("		<a class=\"btn btn-light my-2 my-sm-0 mr-2\" href=\"#\" data-toggle=\"modal\" data-target=\"#exampleModal\"\r\n");
      out.write("			type=\"submit\"><i class=\"fa fa-user-circle-o mr-1\"\r\n");
      out.write("			aria-hidden=\"true\"></i>");
      out.print( user.getName() );
      out.write("\r\n");
      out.write("			</a> <a class=\"btn btn-light my-2 my-sm-0\"\r\n");
      out.write("			href=\"LogoutServlet\" type=\"submit\"><i class=\"fa fa-user-plus mr-1\"\r\n");
      out.write("			aria-hidden=\"true\"></i>Logout</a>\r\n");
      out.write("			<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("       <div class = \"container text-center\">\r\n");
      out.write("       \r\n");
      out.write("       			<i class = \"fa fa-user fa-3x\"></i>\r\n");
      out.write("       			<h5></h5>\r\n");
      out.write("       			<table class = \"table\">\r\n");
      out.write("       				<tbody>\r\n");
      out.write("       					<tr>\r\n");
      out.write("       					<th>User id </th>\r\n");
      out.write("       					<td>");
      out.print( user.getId() );
      out.write("</td>\r\n");
      out.write("       					</tr>\r\n");
      out.write("       					<tr>\r\n");
      out.write("       					<th>full name </th>\r\n");
      out.write("       					<td>");
      out.print( user.getName() );
      out.write("</td>\r\n");
      out.write("       					</tr>\r\n");
      out.write("       					<tr>\r\n");
      out.write("       					<th>Email id </th>\r\n");
      out.write("       					<td>");
      out.print( user.getEmail() );
      out.write("</td>\r\n");
      out.write("       					</tr>\r\n");
      out.write("       				</tbody>\r\n");
      out.write("       		</table>   \r\n");
      out.write("       		<div>\r\n");
      out.write("       		   <button type = \"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">close</button>\r\n");
      out.write("       		\r\n");
      out.write("       		</div> \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<a class=\"btn btn-light my-2 my-sm-0 mr-2\" href=\"login.jsp\"\r\n");
      out.write("			type=\"submit\"><i class=\"fa fa-user-circle-o mr-1\"\r\n");
      out.write("			aria-hidden=\"true\"></i>Login</a> <a class=\"btn btn-light my-2 my-sm-0\"\r\n");
      out.write("			href=\"register.jsp\" type=\"submit\"><i class=\"fa fa-user-plus mr-1\"\r\n");
      out.write("			aria-hidden=\"true\"></i>Register</a>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- Button trigger modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String updateemsg = (String) session.getAttribute("updatemsg");

	if (updateemsg != null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"alert alert-success\" role=\"alert\">");
      out.print(updateemsg);
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	session.removeAttribute("updatemsg");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String wrongmsg = (String) session.getAttribute("wrongmsg");

	if (wrongmsg != null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"alert alert-danger\" role=\"alert\">");
      out.print( wrongmsg );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	session.removeAttribute("wrongmsg");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2 class=\"text-center\">All Notes</h2>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("\r\n");
      out.write("				");

				if (user3 != null) {
					PostDao ob = new PostDao(DBConnect.getConn());
					List<Post> post = ob.getData(user3.getId());
					for (Post po : post) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"card mt-3\">\r\n");
      out.write("\r\n");
      out.write("					<img alt=\"\" src=\"IMG/paper.jpg\" class=\"card-img-top mt-2 ms-auto\"\r\n");
      out.write("						style=\"max-width: 100px;\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card-body p-4\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<h5 class=\"card-title\">");
      out.print(po.getTitle());
      out.write("</h5>\r\n");
      out.write("						<p>");
      out.print(po.getContent());
      out.write("</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<b class=\"text-succes\">published by :");
      out.print(user3.getName());
      out.write(".\r\n");
      out.write("							</b><br> <b class=\"text-primary\">published date :");
      out.print(po.getPdate());
      out.write("</b>\r\n");
      out.write("						</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"container text-center mt-2\">\r\n");
      out.write("							<a href=\"DeleteServlet?note_id=");
      out.print(po.getId());
      out.write("\"\r\n");
      out.write("								class=\"btn btn-danger\">Delte</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a href=\"edit.jsp?note_id=");
      out.print(po.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary\">Edit</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

			}

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<div class=\"container-fluid bg-dark\">\r\n");
      out.write("<p class=\"text-center text-white\">Note: ANY Errors occur then contact CodeWith REGex .Designed and Develeoped by pabitra Das</p>\r\n");
      out.write("<p class=\"text-center text-white\">All reight Reserved @AjayKumarBansal 2025</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
